wip

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -34,7 +34,7 @@ pipeline {
                         echo "========= xml file after sed ============="
                         type $xmlFile
                         echo "============"
-                    """
+                    """ || error("Could not run python")
                 }
             }
         }
